//
//  UIColor+FTMAdditions.swift
//
//  Generated by Zeplin on 9/29/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class func ftmDarkSkyBlueColor() -> UIColor {
		return UIColor(red: 62.0 / 255.0, green: 173.0 / 255.0, blue: 236.0 / 255.0, alpha: 1.0)
	}
}
